// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Fri, 25 May 2018 19:22:06 BST.
// By https://git.io/c-for-go. DO NOT EDIT.

#include "_cgo_export.h"
#include "cgo_helpers.h"

YGSize YGMeasureFunc_ecadcdc6(YGNodeRef node, float width, YGMeasureMode widthMode, float height, YGMeasureMode heightMode) {
	return measureFuncECADCDC6(node, width, widthMode, height, heightMode);
}

float YGBaselineFunc_e756b14a(YGNodeRef node, float width, float height) {
	return baselineFuncE756B14A(node, width, height);
}

void YGDirtiedFunc_91998949(YGNodeRef node) {
	dirtiedFunc91998949(node);
}

void YGPrintFunc_6b37638d(YGNodeRef node) {
	printFunc6B37638D(node);
}

void YGNodeClonedFunc_eb86e6d6(YGNodeRef oldNode, YGNodeRef newNode, YGNodeRef parent, int childIndex) {
	nodeClonedFuncEB86E6D6(oldNode, newNode, parent, childIndex);
}

