// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Thu, 24 May 2018 23:03:41 BST.
// By https://git.io/c-for-go. DO NOT EDIT.

#include "Yoga.h"
#include <stdlib.h>
#pragma once

#define __CGOGEN 1

// YGMeasureFunc_ecadcdc6 is a proxy for callback YGMeasureFunc.
YGSize YGMeasureFunc_ecadcdc6(YGNodeRef node, float width, YGMeasureMode widthMode, float height, YGMeasureMode heightMode);

// YGBaselineFunc_e756b14a is a proxy for callback YGBaselineFunc.
float YGBaselineFunc_e756b14a(YGNodeRef node, float width, float height);

// YGDirtiedFunc_91998949 is a proxy for callback YGDirtiedFunc.
void YGDirtiedFunc_91998949(YGNodeRef node);

// YGPrintFunc_6b37638d is a proxy for callback YGPrintFunc.
void YGPrintFunc_6b37638d(YGNodeRef node);

// YGNodeClonedFunc_eb86e6d6 is a proxy for callback YGNodeClonedFunc.
void YGNodeClonedFunc_eb86e6d6(YGNodeRef oldNode, YGNodeRef newNode, YGNodeRef parent, int childIndex);

