// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Fri, 25 May 2018 19:22:06 BST.
// By https://git.io/c-for-go. DO NOT EDIT.

package yoga

/*
#cgo CFLAGS: -fno-omit-frame-pointer -O3 -fPIC
#cgo CXXFLAGS: -std=c++1y
#cgo LDFLAGS: -lm -lstdc++
#include "Yoga.h"
#include <stdlib.h>
#include "cgo_helpers.h"
*/
import "C"

const (
	// Undefined as defined in yoga/Yoga.h:28
	Undefined = 1e+21
	// AlignCount as defined in yoga/YGEnums.h:14
	AlignCount = 8
	// DimensionCount as defined in yoga/YGEnums.h:27
	DimensionCount = 2
	// DirectionCount as defined in yoga/YGEnums.h:34
	DirectionCount = 3
	// DisplayCount as defined in yoga/YGEnums.h:42
	DisplayCount = 2
	// EdgeCount as defined in yoga/YGEnums.h:49
	EdgeCount = 9
	// ExperimentalFeatureCount as defined in yoga/YGEnums.h:63
	ExperimentalFeatureCount = 1
	// FlexDirectionCount as defined in yoga/YGEnums.h:69
	FlexDirectionCount = 4
	// JustifyCount as defined in yoga/YGEnums.h:78
	JustifyCount = 6
	// LogLevelCount as defined in yoga/YGEnums.h:89
	LogLevelCount = 6
	// MeasureModeCount as defined in yoga/YGEnums.h:100
	MeasureModeCount = 3
	// NodeTypeCount as defined in yoga/YGEnums.h:108
	NodeTypeCount = 2
	// OverflowCount as defined in yoga/YGEnums.h:115
	OverflowCount = 3
	// PositionTypeCount as defined in yoga/YGEnums.h:123
	PositionTypeCount = 2
	// PrintOptionsCount as defined in yoga/YGEnums.h:130
	PrintOptionsCount = 3
	// UnitCount as defined in yoga/YGEnums.h:138
	UnitCount = 4
	// WrapCount as defined in yoga/YGEnums.h:147
	WrapCount = 3
)

// Align as declared in yoga/YGEnums.h:24
type Align int32

// Align enumeration from yoga/YGEnums.h:24
const (
	AlignAuto         Align = iota
	AlignFlexStart    Align = 1
	AlignCenter       Align = 2
	AlignFlexEnd      Align = 3
	AlignStretch      Align = 4
	AlignBaseline     Align = 5
	AlignSpaceBetween Align = 6
	AlignSpaceAround  Align = 7
)

// Dimension as declared in yoga/YGEnums.h:31
type Dimension int32

// Dimension enumeration from yoga/YGEnums.h:31
const (
	DimensionWidth  Dimension = iota
	DimensionHeight Dimension = 1
)

// Direction as declared in yoga/YGEnums.h:39
type Direction int32

// Direction enumeration from yoga/YGEnums.h:39
const (
	DirectionInherit Direction = iota
	DirectionLTR     Direction = 1
	DirectionRTL     Direction = 2
)

// Display as declared in yoga/YGEnums.h:46
type Display int32

// Display enumeration from yoga/YGEnums.h:46
const (
	DisplayFlex Display = iota
	DisplayNone Display = 1
)

// Edge as declared in yoga/YGEnums.h:60
type Edge int32

// Edge enumeration from yoga/YGEnums.h:60
const (
	EdgeLeft       Edge = iota
	EdgeTop        Edge = 1
	EdgeRight      Edge = 2
	EdgeBottom     Edge = 3
	EdgeStart      Edge = 4
	EdgeEnd        Edge = 5
	EdgeHorizontal Edge = 6
	EdgeVertical   Edge = 7
	EdgeAll        Edge = 8
)

// ExperimentalFeature as declared in yoga/YGEnums.h:66
type ExperimentalFeature int32

// ExperimentalFeature enumeration from yoga/YGEnums.h:66
const (
	ExperimentalFeatureWebFlexBasis ExperimentalFeature = iota
)

// FlexDirection as declared in yoga/YGEnums.h:75
type FlexDirection int32

// FlexDirection enumeration from yoga/YGEnums.h:75
const (
	FlexDirectionColumn        FlexDirection = iota
	FlexDirectionColumnReverse FlexDirection = 1
	FlexDirectionRow           FlexDirection = 2
	FlexDirectionRowReverse    FlexDirection = 3
)

// Justify as declared in yoga/YGEnums.h:86
type Justify int32

// Justify enumeration from yoga/YGEnums.h:86
const (
	JustifyFlexStart    Justify = iota
	JustifyCenter       Justify = 1
	JustifyFlexEnd      Justify = 2
	JustifySpaceBetween Justify = 3
	JustifySpaceAround  Justify = 4
	JustifySpaceEvenly  Justify = 5
)

// LogLevel as declared in yoga/YGEnums.h:97
type LogLevel int32

// LogLevel enumeration from yoga/YGEnums.h:97
const (
	LogLevelError   LogLevel = iota
	LogLevelWarn    LogLevel = 1
	LogLevelInfo    LogLevel = 2
	LogLevelDebug   LogLevel = 3
	LogLevelVerbose LogLevel = 4
	LogLevelFatal   LogLevel = 5
)

// MeasureMode as declared in yoga/YGEnums.h:105
type MeasureMode int32

// MeasureMode enumeration from yoga/YGEnums.h:105
const (
	MeasureModeUndefined MeasureMode = iota
	MeasureModeExactly   MeasureMode = 1
	MeasureModeAtMost    MeasureMode = 2
)

// NodeType as declared in yoga/YGEnums.h:112
type NodeType int32

// NodeType enumeration from yoga/YGEnums.h:112
const (
	NodeTypeDefault NodeType = iota
	NodeTypeText    NodeType = 1
)

// Overflow as declared in yoga/YGEnums.h:120
type Overflow int32

// Overflow enumeration from yoga/YGEnums.h:120
const (
	OverflowVisible Overflow = iota
	OverflowHidden  Overflow = 1
	OverflowScroll  Overflow = 2
)

// PositionType as declared in yoga/YGEnums.h:127
type PositionType int32

// PositionType enumeration from yoga/YGEnums.h:127
const (
	PositionTypeRelative PositionType = iota
	PositionTypeAbsolute PositionType = 1
)

// PrintOptions as declared in yoga/YGEnums.h:135
type PrintOptions int32

// PrintOptions enumeration from yoga/YGEnums.h:135
const (
	PrintOptionsLayout   PrintOptions = 1
	PrintOptionsStyle    PrintOptions = 2
	PrintOptionsChildren PrintOptions = 4
)

// Unit as declared in yoga/YGEnums.h:144
type Unit int32

// Unit enumeration from yoga/YGEnums.h:144
const (
	UnitUndefined Unit = iota
	UnitPoint     Unit = 1
	UnitPercent   Unit = 2
	UnitAuto      Unit = 3
)

// Wrap as declared in yoga/YGEnums.h:152
type Wrap int32

// Wrap enumeration from yoga/YGEnums.h:152
const (
	WrapNoWrap      Wrap = iota
	WrapWrap        Wrap = 1
	WrapWrapReverse Wrap = 2
)

const ()

// __codecvt_result as declared in bits/libio.h:180
type __codecvt_result int32

// __codecvt_result enumeration from bits/libio.h:180
const ()
