// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Thu, 24 May 2018 23:03:41 BST.
// By https://git.io/c-for-go. DO NOT EDIT.

/*
Package yoga provides Go bindings for Facebook, Inc's Yoga layout engine
*/
package yoga
