// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Thu, 24 May 2018 23:03:41 BST.
// By https://git.io/c-for-go. DO NOT EDIT.

package yoga

/*
#cgo CFLAGS: -fno-omit-frame-pointer -O3 -fPIC
#cgo CXXFLAGS: -std=c++1y
#cgo LDFLAGS: -lm -lstdc++
#include "Yoga.h"
#include <stdlib.h>
#include "cgo_helpers.h"
*/
import "C"

// Size as declared in yoga/Yoga.h:38
type Size struct {
	Width         float32
	Height        float32
	ref626288d    *C.YGSize
	allocs626288d interface{}
}

// Value as declared in yoga/Yoga.h:43
type Value struct {
	Value          float32
	Unit           Unit
	ref23e8c9e3    *C.YGValue
	allocs23e8c9e3 interface{}
}

// ConfigRef as declared in yoga/Yoga.h:48
type ConfigRef C.YGConfigRef

// NodeRef as declared in yoga/Yoga.h:50
type NodeRef C.YGNodeRef

// MeasureFunc type as declared in yoga/Yoga.h:52
type MeasureFunc func(node NodeRef, width float32, widthMode MeasureMode, height float32, heightMode MeasureMode) Size

// BaselineFunc type as declared in yoga/Yoga.h:57
type BaselineFunc func(node NodeRef, width float32, height float32) float32

// DirtiedFunc type as declared in yoga/Yoga.h:58
type DirtiedFunc func(node NodeRef)

// PrintFunc type as declared in yoga/Yoga.h:59
type PrintFunc func(node NodeRef)

// NodeClonedFunc type as declared in yoga/Yoga.h:65
type NodeClonedFunc func(oldNode NodeRef, newNode NodeRef, parent NodeRef, childIndex int32)
