// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Thu, 24 May 2018 23:03:41 BST.
// By https://git.io/c-for-go. DO NOT EDIT.

package yoga

/*
#cgo CFLAGS: -fno-omit-frame-pointer -O3 -fPIC
#cgo CXXFLAGS: -std=c++1y
#cgo LDFLAGS: -lm -lstdc++
#include "Yoga.h"
#include <stdlib.h>
#include "cgo_helpers.h"
*/
import "C"
import "unsafe"

var ValueUndefined Value
var ValueAuto Value

// NodeNew function as declared in yoga/Yoga.h:71
func NodeNew() NodeRef {
	__ret := C.YGNodeNew()
	__v := *(*NodeRef)(unsafe.Pointer(&__ret))
	return __v
}

// NodeNewWithConfig function as declared in yoga/Yoga.h:72
func NodeNewWithConfig(config ConfigRef) NodeRef {
	cconfig, _ := *(*C.YGConfigRef)(unsafe.Pointer(&config)), cgoAllocsUnknown
	__ret := C.YGNodeNewWithConfig(cconfig)
	__v := *(*NodeRef)(unsafe.Pointer(&__ret))
	return __v
}

// NodeClone function as declared in yoga/Yoga.h:73
func NodeClone(node NodeRef) NodeRef {
	cnode, _ := *(*C.YGNodeRef)(unsafe.Pointer(&node)), cgoAllocsUnknown
	__ret := C.YGNodeClone(cnode)
	__v := *(*NodeRef)(unsafe.Pointer(&__ret))
	return __v
}

// NodeFree function as declared in yoga/Yoga.h:74
func NodeFree(node NodeRef) {
	cnode, _ := *(*C.YGNodeRef)(unsafe.Pointer(&node)), cgoAllocsUnknown
	C.YGNodeFree(cnode)
}

// NodeFreeRecursive function as declared in yoga/Yoga.h:75
func NodeFreeRecursive(node NodeRef) {
	cnode, _ := *(*C.YGNodeRef)(unsafe.Pointer(&node)), cgoAllocsUnknown
	C.YGNodeFreeRecursive(cnode)
}

// NodeReset function as declared in yoga/Yoga.h:76
func NodeReset(node NodeRef) {
	cnode, _ := *(*C.YGNodeRef)(unsafe.Pointer(&node)), cgoAllocsUnknown
	C.YGNodeReset(cnode)
}

// NodeGetInstanceCount function as declared in yoga/Yoga.h:77
func NodeGetInstanceCount() int32 {
	__ret := C.YGNodeGetInstanceCount()
	__v := (int32)(__ret)
	return __v
}

// NodeInsertChild function as declared in yoga/Yoga.h:79
func NodeInsertChild(node NodeRef, child NodeRef, index uint32) {
	cnode, _ := *(*C.YGNodeRef)(unsafe.Pointer(&node)), cgoAllocsUnknown
	cchild, _ := *(*C.YGNodeRef)(unsafe.Pointer(&child)), cgoAllocsUnknown
	cindex, _ := (C.uint32_t)(index), cgoAllocsUnknown
	C.YGNodeInsertChild(cnode, cchild, cindex)
}

// NodeRemoveChild function as declared in yoga/Yoga.h:82
func NodeRemoveChild(node NodeRef, child NodeRef) {
	cnode, _ := *(*C.YGNodeRef)(unsafe.Pointer(&node)), cgoAllocsUnknown
	cchild, _ := *(*C.YGNodeRef)(unsafe.Pointer(&child)), cgoAllocsUnknown
	C.YGNodeRemoveChild(cnode, cchild)
}

// NodeRemoveAllChildren function as declared in yoga/Yoga.h:83
func NodeRemoveAllChildren(node NodeRef) {
	cnode, _ := *(*C.YGNodeRef)(unsafe.Pointer(&node)), cgoAllocsUnknown
	C.YGNodeRemoveAllChildren(cnode)
}

// NodeGetChild function as declared in yoga/Yoga.h:84
func NodeGetChild(node NodeRef, index uint32) NodeRef {
	cnode, _ := *(*C.YGNodeRef)(unsafe.Pointer(&node)), cgoAllocsUnknown
	cindex, _ := (C.uint32_t)(index), cgoAllocsUnknown
	__ret := C.YGNodeGetChild(cnode, cindex)
	__v := *(*NodeRef)(unsafe.Pointer(&__ret))
	return __v
}

// NodeGetParent function as declared in yoga/Yoga.h:85
func NodeGetParent(node NodeRef) NodeRef {
	cnode, _ := *(*C.YGNodeRef)(unsafe.Pointer(&node)), cgoAllocsUnknown
	__ret := C.YGNodeGetParent(cnode)
	__v := *(*NodeRef)(unsafe.Pointer(&__ret))
	return __v
}

// NodeGetChildCount function as declared in yoga/Yoga.h:86
func NodeGetChildCount(node NodeRef) uint32 {
	cnode, _ := *(*C.YGNodeRef)(unsafe.Pointer(&node)), cgoAllocsUnknown
	__ret := C.YGNodeGetChildCount(cnode)
	__v := (uint32)(__ret)
	return __v
}

// NodeCalculateLayout function as declared in yoga/Yoga.h:88
func NodeCalculateLayout(node NodeRef, availableWidth float32, availableHeight float32, parentDirection Direction) {
	cnode, _ := *(*C.YGNodeRef)(unsafe.Pointer(&node)), cgoAllocsUnknown
	cavailableWidth, _ := (C.float)(availableWidth), cgoAllocsUnknown
	cavailableHeight, _ := (C.float)(availableHeight), cgoAllocsUnknown
	cparentDirection, _ := (C.YGDirection)(parentDirection), cgoAllocsUnknown
	C.YGNodeCalculateLayout(cnode, cavailableWidth, cavailableHeight, cparentDirection)
}

// NodeMarkDirty function as declared in yoga/Yoga.h:99
func NodeMarkDirty(node NodeRef) {
	cnode, _ := *(*C.YGNodeRef)(unsafe.Pointer(&node)), cgoAllocsUnknown
	C.YGNodeMarkDirty(cnode)
}

// NodeMarkDirtyAndPropogateToDescendants function as declared in yoga/Yoga.h:103
func NodeMarkDirtyAndPropogateToDescendants(node NodeRef) {
	cnode, _ := *(*C.YGNodeRef)(unsafe.Pointer(&node)), cgoAllocsUnknown
	C.YGNodeMarkDirtyAndPropogateToDescendants(cnode)
}

// NodePrint function as declared in yoga/Yoga.h:105
func NodePrint(node NodeRef, options PrintOptions) {
	cnode, _ := *(*C.YGNodeRef)(unsafe.Pointer(&node)), cgoAllocsUnknown
	coptions, _ := (C.YGPrintOptions)(options), cgoAllocsUnknown
	C.YGNodePrint(cnode, coptions)
}

// FloatIsUndefined function as declared in yoga/Yoga.h:107
func FloatIsUndefined(value float32) bool {
	cvalue, _ := (C.float)(value), cgoAllocsUnknown
	__ret := C.YGFloatIsUndefined(cvalue)
	__v := (bool)(__ret)
	return __v
}

// NodeCanUseCachedMeasurement function as declared in yoga/Yoga.h:109
func NodeCanUseCachedMeasurement(widthMode MeasureMode, width float32, heightMode MeasureMode, height float32, lastWidthMode MeasureMode, lastWidth float32, lastHeightMode MeasureMode, lastHeight float32, lastComputedWidth float32, lastComputedHeight float32, marginRow float32, marginColumn float32, config ConfigRef) bool {
	cwidthMode, _ := (C.YGMeasureMode)(widthMode), cgoAllocsUnknown
	cwidth, _ := (C.float)(width), cgoAllocsUnknown
	cheightMode, _ := (C.YGMeasureMode)(heightMode), cgoAllocsUnknown
	cheight, _ := (C.float)(height), cgoAllocsUnknown
	clastWidthMode, _ := (C.YGMeasureMode)(lastWidthMode), cgoAllocsUnknown
	clastWidth, _ := (C.float)(lastWidth), cgoAllocsUnknown
	clastHeightMode, _ := (C.YGMeasureMode)(lastHeightMode), cgoAllocsUnknown
	clastHeight, _ := (C.float)(lastHeight), cgoAllocsUnknown
	clastComputedWidth, _ := (C.float)(lastComputedWidth), cgoAllocsUnknown
	clastComputedHeight, _ := (C.float)(lastComputedHeight), cgoAllocsUnknown
	cmarginRow, _ := (C.float)(marginRow), cgoAllocsUnknown
	cmarginColumn, _ := (C.float)(marginColumn), cgoAllocsUnknown
	cconfig, _ := *(*C.YGConfigRef)(unsafe.Pointer(&config)), cgoAllocsUnknown
	__ret := C.YGNodeCanUseCachedMeasurement(cwidthMode, cwidth, cheightMode, cheight, clastWidthMode, clastWidth, clastHeightMode, clastHeight, clastComputedWidth, clastComputedHeight, cmarginRow, cmarginColumn, cconfig)
	__v := (bool)(__ret)
	return __v
}

// NodeCopyStyle function as declared in yoga/Yoga.h:123
func NodeCopyStyle(dstNode NodeRef, srcNode NodeRef) {
	cdstNode, _ := *(*C.YGNodeRef)(unsafe.Pointer(&dstNode)), cgoAllocsUnknown
	csrcNode, _ := *(*C.YGNodeRef)(unsafe.Pointer(&srcNode)), cgoAllocsUnknown
	C.YGNodeCopyStyle(cdstNode, csrcNode)
}

// NodeGetContext function as declared in yoga/Yoga.h:166
func NodeGetContext(node NodeRef) unsafe.Pointer {
	cnode, _ := *(*C.YGNodeRef)(unsafe.Pointer(&node)), cgoAllocsUnknown
	__ret := C.YGNodeGetContext(cnode)
	__v := *(*unsafe.Pointer)(unsafe.Pointer(&__ret))
	return __v
}

// NodeSetContext function as declared in yoga/Yoga.h:167
func NodeSetContext(node NodeRef, context unsafe.Pointer) {
	cnode, _ := *(*C.YGNodeRef)(unsafe.Pointer(&node)), cgoAllocsUnknown
	ccontext, _ := context, cgoAllocsUnknown
	C.YGNodeSetContext(cnode, ccontext)
}

// NodeGetMeasureFunc function as declared in yoga/Yoga.h:168
func NodeGetMeasureFunc(node NodeRef) MeasureFunc {
	cnode, _ := *(*C.YGNodeRef)(unsafe.Pointer(&node)), cgoAllocsUnknown
	__ret := C.YGNodeGetMeasureFunc(cnode)
	__v := *NewMeasureFuncRef(unsafe.Pointer(&__ret))
	return __v
}

// NodeSetMeasureFunc function as declared in yoga/Yoga.h:169
func NodeSetMeasureFunc(node NodeRef, measureFunc MeasureFunc) {
	cnode, _ := *(*C.YGNodeRef)(unsafe.Pointer(&node)), cgoAllocsUnknown
	cmeasureFunc, _ := measureFunc.PassValue()
	C.YGNodeSetMeasureFunc(cnode, cmeasureFunc)
}

// NodeGetBaselineFunc function as declared in yoga/Yoga.h:170
func NodeGetBaselineFunc(node NodeRef) BaselineFunc {
	cnode, _ := *(*C.YGNodeRef)(unsafe.Pointer(&node)), cgoAllocsUnknown
	__ret := C.YGNodeGetBaselineFunc(cnode)
	__v := *NewBaselineFuncRef(unsafe.Pointer(&__ret))
	return __v
}

// NodeSetBaselineFunc function as declared in yoga/Yoga.h:171
func NodeSetBaselineFunc(node NodeRef, baselineFunc BaselineFunc) {
	cnode, _ := *(*C.YGNodeRef)(unsafe.Pointer(&node)), cgoAllocsUnknown
	cbaselineFunc, _ := baselineFunc.PassValue()
	C.YGNodeSetBaselineFunc(cnode, cbaselineFunc)
}

// NodeGetDirtiedFunc function as declared in yoga/Yoga.h:172
func NodeGetDirtiedFunc(node NodeRef) DirtiedFunc {
	cnode, _ := *(*C.YGNodeRef)(unsafe.Pointer(&node)), cgoAllocsUnknown
	__ret := C.YGNodeGetDirtiedFunc(cnode)
	__v := *NewDirtiedFuncRef(unsafe.Pointer(&__ret))
	return __v
}

// NodeSetDirtiedFunc function as declared in yoga/Yoga.h:173
func NodeSetDirtiedFunc(node NodeRef, dirtiedFunc DirtiedFunc) {
	cnode, _ := *(*C.YGNodeRef)(unsafe.Pointer(&node)), cgoAllocsUnknown
	cdirtiedFunc, _ := dirtiedFunc.PassValue()
	C.YGNodeSetDirtiedFunc(cnode, cdirtiedFunc)
}

// NodeGetPrintFunc function as declared in yoga/Yoga.h:174
func NodeGetPrintFunc(node NodeRef) PrintFunc {
	cnode, _ := *(*C.YGNodeRef)(unsafe.Pointer(&node)), cgoAllocsUnknown
	__ret := C.YGNodeGetPrintFunc(cnode)
	__v := *NewPrintFuncRef(unsafe.Pointer(&__ret))
	return __v
}

// NodeSetPrintFunc function as declared in yoga/Yoga.h:175
func NodeSetPrintFunc(node NodeRef, printFunc PrintFunc) {
	cnode, _ := *(*C.YGNodeRef)(unsafe.Pointer(&node)), cgoAllocsUnknown
	cprintFunc, _ := printFunc.PassValue()
	C.YGNodeSetPrintFunc(cnode, cprintFunc)
}

// NodeGetHasNewLayout function as declared in yoga/Yoga.h:176
func NodeGetHasNewLayout(node NodeRef) bool {
	cnode, _ := *(*C.YGNodeRef)(unsafe.Pointer(&node)), cgoAllocsUnknown
	__ret := C.YGNodeGetHasNewLayout(cnode)
	__v := (bool)(__ret)
	return __v
}

// NodeSetHasNewLayout function as declared in yoga/Yoga.h:177
func NodeSetHasNewLayout(node NodeRef, hasNewLayout bool) {
	cnode, _ := *(*C.YGNodeRef)(unsafe.Pointer(&node)), cgoAllocsUnknown
	chasNewLayout, _ := (C._Bool)(hasNewLayout), cgoAllocsUnknown
	C.YGNodeSetHasNewLayout(cnode, chasNewLayout)
}

// NodeGetNodeType function as declared in yoga/Yoga.h:178
func NodeGetNodeType(node NodeRef) NodeType {
	cnode, _ := *(*C.YGNodeRef)(unsafe.Pointer(&node)), cgoAllocsUnknown
	__ret := C.YGNodeGetNodeType(cnode)
	__v := (NodeType)(__ret)
	return __v
}

// NodeSetNodeType function as declared in yoga/Yoga.h:179
func NodeSetNodeType(node NodeRef, nodeType NodeType) {
	cnode, _ := *(*C.YGNodeRef)(unsafe.Pointer(&node)), cgoAllocsUnknown
	cnodeType, _ := (C.YGNodeType)(nodeType), cgoAllocsUnknown
	C.YGNodeSetNodeType(cnode, cnodeType)
}

// NodeIsDirty function as declared in yoga/Yoga.h:180
func NodeIsDirty(node NodeRef) bool {
	cnode, _ := *(*C.YGNodeRef)(unsafe.Pointer(&node)), cgoAllocsUnknown
	__ret := C.YGNodeIsDirty(cnode)
	__v := (bool)(__ret)
	return __v
}

// NodeLayoutGetDidUseLegacyFlag function as declared in yoga/Yoga.h:181
func NodeLayoutGetDidUseLegacyFlag(node NodeRef) bool {
	cnode, _ := *(*C.YGNodeRef)(unsafe.Pointer(&node)), cgoAllocsUnknown
	__ret := C.YGNodeLayoutGetDidUseLegacyFlag(cnode)
	__v := (bool)(__ret)
	return __v
}

// NodeStyleGetDirection function as declared in yoga/Yoga.h:183
func NodeStyleGetDirection(node NodeRef) Direction {
	cnode, _ := *(*C.YGNodeRef)(unsafe.Pointer(&node)), cgoAllocsUnknown
	__ret := C.YGNodeStyleGetDirection(cnode)
	__v := (Direction)(__ret)
	return __v
}

// NodeStyleSetDirection function as declared in yoga/Yoga.h:183
func NodeStyleSetDirection(node NodeRef, direction Direction) {
	cnode, _ := *(*C.YGNodeRef)(unsafe.Pointer(&node)), cgoAllocsUnknown
	cdirection, _ := (C.YGDirection)(direction), cgoAllocsUnknown
	C.YGNodeStyleSetDirection(cnode, cdirection)
}

// NodeStyleGetFlexDirection function as declared in yoga/Yoga.h:184
func NodeStyleGetFlexDirection(node NodeRef) FlexDirection {
	cnode, _ := *(*C.YGNodeRef)(unsafe.Pointer(&node)), cgoAllocsUnknown
	__ret := C.YGNodeStyleGetFlexDirection(cnode)
	__v := (FlexDirection)(__ret)
	return __v
}

// NodeStyleSetFlexDirection function as declared in yoga/Yoga.h:184
func NodeStyleSetFlexDirection(node NodeRef, flexDirection FlexDirection) {
	cnode, _ := *(*C.YGNodeRef)(unsafe.Pointer(&node)), cgoAllocsUnknown
	cflexDirection, _ := (C.YGFlexDirection)(flexDirection), cgoAllocsUnknown
	C.YGNodeStyleSetFlexDirection(cnode, cflexDirection)
}

// NodeStyleGetJustifyContent function as declared in yoga/Yoga.h:185
func NodeStyleGetJustifyContent(node NodeRef) Justify {
	cnode, _ := *(*C.YGNodeRef)(unsafe.Pointer(&node)), cgoAllocsUnknown
	__ret := C.YGNodeStyleGetJustifyContent(cnode)
	__v := (Justify)(__ret)
	return __v
}

// NodeStyleSetJustifyContent function as declared in yoga/Yoga.h:185
func NodeStyleSetJustifyContent(node NodeRef, justifyContent Justify) {
	cnode, _ := *(*C.YGNodeRef)(unsafe.Pointer(&node)), cgoAllocsUnknown
	cjustifyContent, _ := (C.YGJustify)(justifyContent), cgoAllocsUnknown
	C.YGNodeStyleSetJustifyContent(cnode, cjustifyContent)
}

// NodeStyleGetAlignContent function as declared in yoga/Yoga.h:186
func NodeStyleGetAlignContent(node NodeRef) Align {
	cnode, _ := *(*C.YGNodeRef)(unsafe.Pointer(&node)), cgoAllocsUnknown
	__ret := C.YGNodeStyleGetAlignContent(cnode)
	__v := (Align)(__ret)
	return __v
}

// NodeStyleSetAlignContent function as declared in yoga/Yoga.h:186
func NodeStyleSetAlignContent(node NodeRef, alignContent Align) {
	cnode, _ := *(*C.YGNodeRef)(unsafe.Pointer(&node)), cgoAllocsUnknown
	calignContent, _ := (C.YGAlign)(alignContent), cgoAllocsUnknown
	C.YGNodeStyleSetAlignContent(cnode, calignContent)
}

// NodeStyleGetAlignItems function as declared in yoga/Yoga.h:187
func NodeStyleGetAlignItems(node NodeRef) Align {
	cnode, _ := *(*C.YGNodeRef)(unsafe.Pointer(&node)), cgoAllocsUnknown
	__ret := C.YGNodeStyleGetAlignItems(cnode)
	__v := (Align)(__ret)
	return __v
}

// NodeStyleSetAlignItems function as declared in yoga/Yoga.h:187
func NodeStyleSetAlignItems(node NodeRef, alignItems Align) {
	cnode, _ := *(*C.YGNodeRef)(unsafe.Pointer(&node)), cgoAllocsUnknown
	calignItems, _ := (C.YGAlign)(alignItems), cgoAllocsUnknown
	C.YGNodeStyleSetAlignItems(cnode, calignItems)
}

// NodeStyleGetAlignSelf function as declared in yoga/Yoga.h:188
func NodeStyleGetAlignSelf(node NodeRef) Align {
	cnode, _ := *(*C.YGNodeRef)(unsafe.Pointer(&node)), cgoAllocsUnknown
	__ret := C.YGNodeStyleGetAlignSelf(cnode)
	__v := (Align)(__ret)
	return __v
}

// NodeStyleSetAlignSelf function as declared in yoga/Yoga.h:188
func NodeStyleSetAlignSelf(node NodeRef, alignSelf Align) {
	cnode, _ := *(*C.YGNodeRef)(unsafe.Pointer(&node)), cgoAllocsUnknown
	calignSelf, _ := (C.YGAlign)(alignSelf), cgoAllocsUnknown
	C.YGNodeStyleSetAlignSelf(cnode, calignSelf)
}

// NodeStyleGetPositionType function as declared in yoga/Yoga.h:189
func NodeStyleGetPositionType(node NodeRef) PositionType {
	cnode, _ := *(*C.YGNodeRef)(unsafe.Pointer(&node)), cgoAllocsUnknown
	__ret := C.YGNodeStyleGetPositionType(cnode)
	__v := (PositionType)(__ret)
	return __v
}

// NodeStyleSetPositionType function as declared in yoga/Yoga.h:189
func NodeStyleSetPositionType(node NodeRef, positionType PositionType) {
	cnode, _ := *(*C.YGNodeRef)(unsafe.Pointer(&node)), cgoAllocsUnknown
	cpositionType, _ := (C.YGPositionType)(positionType), cgoAllocsUnknown
	C.YGNodeStyleSetPositionType(cnode, cpositionType)
}

// NodeStyleGetFlexWrap function as declared in yoga/Yoga.h:190
func NodeStyleGetFlexWrap(node NodeRef) Wrap {
	cnode, _ := *(*C.YGNodeRef)(unsafe.Pointer(&node)), cgoAllocsUnknown
	__ret := C.YGNodeStyleGetFlexWrap(cnode)
	__v := (Wrap)(__ret)
	return __v
}

// NodeStyleSetFlexWrap function as declared in yoga/Yoga.h:190
func NodeStyleSetFlexWrap(node NodeRef, flexWrap Wrap) {
	cnode, _ := *(*C.YGNodeRef)(unsafe.Pointer(&node)), cgoAllocsUnknown
	cflexWrap, _ := (C.YGWrap)(flexWrap), cgoAllocsUnknown
	C.YGNodeStyleSetFlexWrap(cnode, cflexWrap)
}

// NodeStyleGetOverflow function as declared in yoga/Yoga.h:191
func NodeStyleGetOverflow(node NodeRef) Overflow {
	cnode, _ := *(*C.YGNodeRef)(unsafe.Pointer(&node)), cgoAllocsUnknown
	__ret := C.YGNodeStyleGetOverflow(cnode)
	__v := (Overflow)(__ret)
	return __v
}

// NodeStyleSetOverflow function as declared in yoga/Yoga.h:191
func NodeStyleSetOverflow(node NodeRef, overflow Overflow) {
	cnode, _ := *(*C.YGNodeRef)(unsafe.Pointer(&node)), cgoAllocsUnknown
	coverflow, _ := (C.YGOverflow)(overflow), cgoAllocsUnknown
	C.YGNodeStyleSetOverflow(cnode, coverflow)
}

// NodeStyleGetDisplay function as declared in yoga/Yoga.h:192
func NodeStyleGetDisplay(node NodeRef) Display {
	cnode, _ := *(*C.YGNodeRef)(unsafe.Pointer(&node)), cgoAllocsUnknown
	__ret := C.YGNodeStyleGetDisplay(cnode)
	__v := (Display)(__ret)
	return __v
}

// NodeStyleSetDisplay function as declared in yoga/Yoga.h:192
func NodeStyleSetDisplay(node NodeRef, display Display) {
	cnode, _ := *(*C.YGNodeRef)(unsafe.Pointer(&node)), cgoAllocsUnknown
	cdisplay, _ := (C.YGDisplay)(display), cgoAllocsUnknown
	C.YGNodeStyleSetDisplay(cnode, cdisplay)
}

// NodeStyleGetFlex function as declared in yoga/Yoga.h:194
func NodeStyleGetFlex(node NodeRef) float32 {
	cnode, _ := *(*C.YGNodeRef)(unsafe.Pointer(&node)), cgoAllocsUnknown
	__ret := C.YGNodeStyleGetFlex(cnode)
	__v := (float32)(__ret)
	return __v
}

// NodeStyleSetFlex function as declared in yoga/Yoga.h:194
func NodeStyleSetFlex(node NodeRef, flex float32) {
	cnode, _ := *(*C.YGNodeRef)(unsafe.Pointer(&node)), cgoAllocsUnknown
	cflex, _ := (C.float)(flex), cgoAllocsUnknown
	C.YGNodeStyleSetFlex(cnode, cflex)
}

// NodeStyleGetFlexGrow function as declared in yoga/Yoga.h:195
func NodeStyleGetFlexGrow(node NodeRef) float32 {
	cnode, _ := *(*C.YGNodeRef)(unsafe.Pointer(&node)), cgoAllocsUnknown
	__ret := C.YGNodeStyleGetFlexGrow(cnode)
	__v := (float32)(__ret)
	return __v
}

// NodeStyleSetFlexGrow function as declared in yoga/Yoga.h:195
func NodeStyleSetFlexGrow(node NodeRef, flexGrow float32) {
	cnode, _ := *(*C.YGNodeRef)(unsafe.Pointer(&node)), cgoAllocsUnknown
	cflexGrow, _ := (C.float)(flexGrow), cgoAllocsUnknown
	C.YGNodeStyleSetFlexGrow(cnode, cflexGrow)
}

// NodeStyleGetFlexShrink function as declared in yoga/Yoga.h:196
func NodeStyleGetFlexShrink(node NodeRef) float32 {
	cnode, _ := *(*C.YGNodeRef)(unsafe.Pointer(&node)), cgoAllocsUnknown
	__ret := C.YGNodeStyleGetFlexShrink(cnode)
	__v := (float32)(__ret)
	return __v
}

// NodeStyleSetFlexShrink function as declared in yoga/Yoga.h:196
func NodeStyleSetFlexShrink(node NodeRef, flexShrink float32) {
	cnode, _ := *(*C.YGNodeRef)(unsafe.Pointer(&node)), cgoAllocsUnknown
	cflexShrink, _ := (C.float)(flexShrink), cgoAllocsUnknown
	C.YGNodeStyleSetFlexShrink(cnode, cflexShrink)
}

// NodeStyleGetFlexBasis function as declared in yoga/Yoga.h:197
func NodeStyleGetFlexBasis(node NodeRef) Value {
	cnode, _ := *(*C.YGNodeRef)(unsafe.Pointer(&node)), cgoAllocsUnknown
	__ret := C.YGNodeStyleGetFlexBasis(cnode)
	__v := *NewValueRef(unsafe.Pointer(&__ret))
	return __v
}

// NodeStyleSetFlexBasis function as declared in yoga/Yoga.h:197
func NodeStyleSetFlexBasis(node NodeRef, flexBasis float32) {
	cnode, _ := *(*C.YGNodeRef)(unsafe.Pointer(&node)), cgoAllocsUnknown
	cflexBasis, _ := (C.float)(flexBasis), cgoAllocsUnknown
	C.YGNodeStyleSetFlexBasis(cnode, cflexBasis)
}

// NodeStyleSetFlexBasisAuto function as declared in yoga/Yoga.h:197
func NodeStyleSetFlexBasisAuto(node NodeRef) {
	cnode, _ := *(*C.YGNodeRef)(unsafe.Pointer(&node)), cgoAllocsUnknown
	C.YGNodeStyleSetFlexBasisAuto(cnode)
}

// NodeStyleSetFlexBasisPercent function as declared in yoga/Yoga.h:197
func NodeStyleSetFlexBasisPercent(node NodeRef, flexBasis float32) {
	cnode, _ := *(*C.YGNodeRef)(unsafe.Pointer(&node)), cgoAllocsUnknown
	cflexBasis, _ := (C.float)(flexBasis), cgoAllocsUnknown
	C.YGNodeStyleSetFlexBasisPercent(cnode, cflexBasis)
}

// NodeStyleGetPosition function as declared in yoga/Yoga.h:199
func NodeStyleGetPosition(node NodeRef, edge Edge) Value {
	cnode, _ := *(*C.YGNodeRef)(unsafe.Pointer(&node)), cgoAllocsUnknown
	cedge, _ := (C.YGEdge)(edge), cgoAllocsUnknown
	__ret := C.YGNodeStyleGetPosition(cnode, cedge)
	__v := *NewValueRef(unsafe.Pointer(&__ret))
	return __v
}

// NodeStyleSetPosition function as declared in yoga/Yoga.h:199
func NodeStyleSetPosition(node NodeRef, edge Edge, position float32) {
	cnode, _ := *(*C.YGNodeRef)(unsafe.Pointer(&node)), cgoAllocsUnknown
	cedge, _ := (C.YGEdge)(edge), cgoAllocsUnknown
	cposition, _ := (C.float)(position), cgoAllocsUnknown
	C.YGNodeStyleSetPosition(cnode, cedge, cposition)
}

// NodeStyleSetPositionPercent function as declared in yoga/Yoga.h:199
func NodeStyleSetPositionPercent(node NodeRef, edge Edge, position float32) {
	cnode, _ := *(*C.YGNodeRef)(unsafe.Pointer(&node)), cgoAllocsUnknown
	cedge, _ := (C.YGEdge)(edge), cgoAllocsUnknown
	cposition, _ := (C.float)(position), cgoAllocsUnknown
	C.YGNodeStyleSetPositionPercent(cnode, cedge, cposition)
}

// NodeStyleGetMargin function as declared in yoga/Yoga.h:200
func NodeStyleGetMargin(node NodeRef, edge Edge) Value {
	cnode, _ := *(*C.YGNodeRef)(unsafe.Pointer(&node)), cgoAllocsUnknown
	cedge, _ := (C.YGEdge)(edge), cgoAllocsUnknown
	__ret := C.YGNodeStyleGetMargin(cnode, cedge)
	__v := *NewValueRef(unsafe.Pointer(&__ret))
	return __v
}

// NodeStyleSetMargin function as declared in yoga/Yoga.h:200
func NodeStyleSetMargin(node NodeRef, edge Edge, margin float32) {
	cnode, _ := *(*C.YGNodeRef)(unsafe.Pointer(&node)), cgoAllocsUnknown
	cedge, _ := (C.YGEdge)(edge), cgoAllocsUnknown
	cmargin, _ := (C.float)(margin), cgoAllocsUnknown
	C.YGNodeStyleSetMargin(cnode, cedge, cmargin)
}

// NodeStyleSetMarginPercent function as declared in yoga/Yoga.h:200
func NodeStyleSetMarginPercent(node NodeRef, edge Edge, margin float32) {
	cnode, _ := *(*C.YGNodeRef)(unsafe.Pointer(&node)), cgoAllocsUnknown
	cedge, _ := (C.YGEdge)(edge), cgoAllocsUnknown
	cmargin, _ := (C.float)(margin), cgoAllocsUnknown
	C.YGNodeStyleSetMarginPercent(cnode, cedge, cmargin)
}

// NodeStyleSetMarginAuto function as declared in yoga/Yoga.h:201
func NodeStyleSetMarginAuto(node NodeRef, edge Edge) {
	cnode, _ := *(*C.YGNodeRef)(unsafe.Pointer(&node)), cgoAllocsUnknown
	cedge, _ := (C.YGEdge)(edge), cgoAllocsUnknown
	C.YGNodeStyleSetMarginAuto(cnode, cedge)
}

// NodeStyleGetPadding function as declared in yoga/Yoga.h:202
func NodeStyleGetPadding(node NodeRef, edge Edge) Value {
	cnode, _ := *(*C.YGNodeRef)(unsafe.Pointer(&node)), cgoAllocsUnknown
	cedge, _ := (C.YGEdge)(edge), cgoAllocsUnknown
	__ret := C.YGNodeStyleGetPadding(cnode, cedge)
	__v := *NewValueRef(unsafe.Pointer(&__ret))
	return __v
}

// NodeStyleSetPadding function as declared in yoga/Yoga.h:202
func NodeStyleSetPadding(node NodeRef, edge Edge, padding float32) {
	cnode, _ := *(*C.YGNodeRef)(unsafe.Pointer(&node)), cgoAllocsUnknown
	cedge, _ := (C.YGEdge)(edge), cgoAllocsUnknown
	cpadding, _ := (C.float)(padding), cgoAllocsUnknown
	C.YGNodeStyleSetPadding(cnode, cedge, cpadding)
}

// NodeStyleSetPaddingPercent function as declared in yoga/Yoga.h:202
func NodeStyleSetPaddingPercent(node NodeRef, edge Edge, padding float32) {
	cnode, _ := *(*C.YGNodeRef)(unsafe.Pointer(&node)), cgoAllocsUnknown
	cedge, _ := (C.YGEdge)(edge), cgoAllocsUnknown
	cpadding, _ := (C.float)(padding), cgoAllocsUnknown
	C.YGNodeStyleSetPaddingPercent(cnode, cedge, cpadding)
}

// NodeStyleGetBorder function as declared in yoga/Yoga.h:203
func NodeStyleGetBorder(node NodeRef, edge Edge) float32 {
	cnode, _ := *(*C.YGNodeRef)(unsafe.Pointer(&node)), cgoAllocsUnknown
	cedge, _ := (C.YGEdge)(edge), cgoAllocsUnknown
	__ret := C.YGNodeStyleGetBorder(cnode, cedge)
	__v := (float32)(__ret)
	return __v
}

// NodeStyleSetBorder function as declared in yoga/Yoga.h:203
func NodeStyleSetBorder(node NodeRef, edge Edge, border float32) {
	cnode, _ := *(*C.YGNodeRef)(unsafe.Pointer(&node)), cgoAllocsUnknown
	cedge, _ := (C.YGEdge)(edge), cgoAllocsUnknown
	cborder, _ := (C.float)(border), cgoAllocsUnknown
	C.YGNodeStyleSetBorder(cnode, cedge, cborder)
}

// NodeStyleGetWidth function as declared in yoga/Yoga.h:205
func NodeStyleGetWidth(node NodeRef) Value {
	cnode, _ := *(*C.YGNodeRef)(unsafe.Pointer(&node)), cgoAllocsUnknown
	__ret := C.YGNodeStyleGetWidth(cnode)
	__v := *NewValueRef(unsafe.Pointer(&__ret))
	return __v
}

// NodeStyleSetWidth function as declared in yoga/Yoga.h:205
func NodeStyleSetWidth(node NodeRef, width float32) {
	cnode, _ := *(*C.YGNodeRef)(unsafe.Pointer(&node)), cgoAllocsUnknown
	cwidth, _ := (C.float)(width), cgoAllocsUnknown
	C.YGNodeStyleSetWidth(cnode, cwidth)
}

// NodeStyleSetWidthAuto function as declared in yoga/Yoga.h:205
func NodeStyleSetWidthAuto(node NodeRef) {
	cnode, _ := *(*C.YGNodeRef)(unsafe.Pointer(&node)), cgoAllocsUnknown
	C.YGNodeStyleSetWidthAuto(cnode)
}

// NodeStyleSetWidthPercent function as declared in yoga/Yoga.h:205
func NodeStyleSetWidthPercent(node NodeRef, width float32) {
	cnode, _ := *(*C.YGNodeRef)(unsafe.Pointer(&node)), cgoAllocsUnknown
	cwidth, _ := (C.float)(width), cgoAllocsUnknown
	C.YGNodeStyleSetWidthPercent(cnode, cwidth)
}

// NodeStyleGetHeight function as declared in yoga/Yoga.h:206
func NodeStyleGetHeight(node NodeRef) Value {
	cnode, _ := *(*C.YGNodeRef)(unsafe.Pointer(&node)), cgoAllocsUnknown
	__ret := C.YGNodeStyleGetHeight(cnode)
	__v := *NewValueRef(unsafe.Pointer(&__ret))
	return __v
}

// NodeStyleSetHeight function as declared in yoga/Yoga.h:206
func NodeStyleSetHeight(node NodeRef, height float32) {
	cnode, _ := *(*C.YGNodeRef)(unsafe.Pointer(&node)), cgoAllocsUnknown
	cheight, _ := (C.float)(height), cgoAllocsUnknown
	C.YGNodeStyleSetHeight(cnode, cheight)
}

// NodeStyleSetHeightAuto function as declared in yoga/Yoga.h:206
func NodeStyleSetHeightAuto(node NodeRef) {
	cnode, _ := *(*C.YGNodeRef)(unsafe.Pointer(&node)), cgoAllocsUnknown
	C.YGNodeStyleSetHeightAuto(cnode)
}

// NodeStyleSetHeightPercent function as declared in yoga/Yoga.h:206
func NodeStyleSetHeightPercent(node NodeRef, height float32) {
	cnode, _ := *(*C.YGNodeRef)(unsafe.Pointer(&node)), cgoAllocsUnknown
	cheight, _ := (C.float)(height), cgoAllocsUnknown
	C.YGNodeStyleSetHeightPercent(cnode, cheight)
}

// NodeStyleGetMinWidth function as declared in yoga/Yoga.h:207
func NodeStyleGetMinWidth(node NodeRef) Value {
	cnode, _ := *(*C.YGNodeRef)(unsafe.Pointer(&node)), cgoAllocsUnknown
	__ret := C.YGNodeStyleGetMinWidth(cnode)
	__v := *NewValueRef(unsafe.Pointer(&__ret))
	return __v
}

// NodeStyleSetMinWidth function as declared in yoga/Yoga.h:207
func NodeStyleSetMinWidth(node NodeRef, minWidth float32) {
	cnode, _ := *(*C.YGNodeRef)(unsafe.Pointer(&node)), cgoAllocsUnknown
	cminWidth, _ := (C.float)(minWidth), cgoAllocsUnknown
	C.YGNodeStyleSetMinWidth(cnode, cminWidth)
}

// NodeStyleSetMinWidthPercent function as declared in yoga/Yoga.h:207
func NodeStyleSetMinWidthPercent(node NodeRef, minWidth float32) {
	cnode, _ := *(*C.YGNodeRef)(unsafe.Pointer(&node)), cgoAllocsUnknown
	cminWidth, _ := (C.float)(minWidth), cgoAllocsUnknown
	C.YGNodeStyleSetMinWidthPercent(cnode, cminWidth)
}

// NodeStyleGetMinHeight function as declared in yoga/Yoga.h:208
func NodeStyleGetMinHeight(node NodeRef) Value {
	cnode, _ := *(*C.YGNodeRef)(unsafe.Pointer(&node)), cgoAllocsUnknown
	__ret := C.YGNodeStyleGetMinHeight(cnode)
	__v := *NewValueRef(unsafe.Pointer(&__ret))
	return __v
}

// NodeStyleSetMinHeight function as declared in yoga/Yoga.h:208
func NodeStyleSetMinHeight(node NodeRef, minHeight float32) {
	cnode, _ := *(*C.YGNodeRef)(unsafe.Pointer(&node)), cgoAllocsUnknown
	cminHeight, _ := (C.float)(minHeight), cgoAllocsUnknown
	C.YGNodeStyleSetMinHeight(cnode, cminHeight)
}

// NodeStyleSetMinHeightPercent function as declared in yoga/Yoga.h:208
func NodeStyleSetMinHeightPercent(node NodeRef, minHeight float32) {
	cnode, _ := *(*C.YGNodeRef)(unsafe.Pointer(&node)), cgoAllocsUnknown
	cminHeight, _ := (C.float)(minHeight), cgoAllocsUnknown
	C.YGNodeStyleSetMinHeightPercent(cnode, cminHeight)
}

// NodeStyleGetMaxWidth function as declared in yoga/Yoga.h:209
func NodeStyleGetMaxWidth(node NodeRef) Value {
	cnode, _ := *(*C.YGNodeRef)(unsafe.Pointer(&node)), cgoAllocsUnknown
	__ret := C.YGNodeStyleGetMaxWidth(cnode)
	__v := *NewValueRef(unsafe.Pointer(&__ret))
	return __v
}

// NodeStyleSetMaxWidth function as declared in yoga/Yoga.h:209
func NodeStyleSetMaxWidth(node NodeRef, maxWidth float32) {
	cnode, _ := *(*C.YGNodeRef)(unsafe.Pointer(&node)), cgoAllocsUnknown
	cmaxWidth, _ := (C.float)(maxWidth), cgoAllocsUnknown
	C.YGNodeStyleSetMaxWidth(cnode, cmaxWidth)
}

// NodeStyleSetMaxWidthPercent function as declared in yoga/Yoga.h:209
func NodeStyleSetMaxWidthPercent(node NodeRef, maxWidth float32) {
	cnode, _ := *(*C.YGNodeRef)(unsafe.Pointer(&node)), cgoAllocsUnknown
	cmaxWidth, _ := (C.float)(maxWidth), cgoAllocsUnknown
	C.YGNodeStyleSetMaxWidthPercent(cnode, cmaxWidth)
}

// NodeStyleGetMaxHeight function as declared in yoga/Yoga.h:210
func NodeStyleGetMaxHeight(node NodeRef) Value {
	cnode, _ := *(*C.YGNodeRef)(unsafe.Pointer(&node)), cgoAllocsUnknown
	__ret := C.YGNodeStyleGetMaxHeight(cnode)
	__v := *NewValueRef(unsafe.Pointer(&__ret))
	return __v
}

// NodeStyleSetMaxHeight function as declared in yoga/Yoga.h:210
func NodeStyleSetMaxHeight(node NodeRef, maxHeight float32) {
	cnode, _ := *(*C.YGNodeRef)(unsafe.Pointer(&node)), cgoAllocsUnknown
	cmaxHeight, _ := (C.float)(maxHeight), cgoAllocsUnknown
	C.YGNodeStyleSetMaxHeight(cnode, cmaxHeight)
}

// NodeStyleSetMaxHeightPercent function as declared in yoga/Yoga.h:210
func NodeStyleSetMaxHeightPercent(node NodeRef, maxHeight float32) {
	cnode, _ := *(*C.YGNodeRef)(unsafe.Pointer(&node)), cgoAllocsUnknown
	cmaxHeight, _ := (C.float)(maxHeight), cgoAllocsUnknown
	C.YGNodeStyleSetMaxHeightPercent(cnode, cmaxHeight)
}

// NodeStyleGetAspectRatio function as declared in yoga/Yoga.h:225
func NodeStyleGetAspectRatio(node NodeRef) float32 {
	cnode, _ := *(*C.YGNodeRef)(unsafe.Pointer(&node)), cgoAllocsUnknown
	__ret := C.YGNodeStyleGetAspectRatio(cnode)
	__v := (float32)(__ret)
	return __v
}

// NodeStyleSetAspectRatio function as declared in yoga/Yoga.h:225
func NodeStyleSetAspectRatio(node NodeRef, aspectRatio float32) {
	cnode, _ := *(*C.YGNodeRef)(unsafe.Pointer(&node)), cgoAllocsUnknown
	caspectRatio, _ := (C.float)(aspectRatio), cgoAllocsUnknown
	C.YGNodeStyleSetAspectRatio(cnode, caspectRatio)
}

// NodeLayoutGetLeft function as declared in yoga/Yoga.h:227
func NodeLayoutGetLeft(node NodeRef) float32 {
	cnode, _ := *(*C.YGNodeRef)(unsafe.Pointer(&node)), cgoAllocsUnknown
	__ret := C.YGNodeLayoutGetLeft(cnode)
	__v := (float32)(__ret)
	return __v
}

// NodeLayoutGetTop function as declared in yoga/Yoga.h:228
func NodeLayoutGetTop(node NodeRef) float32 {
	cnode, _ := *(*C.YGNodeRef)(unsafe.Pointer(&node)), cgoAllocsUnknown
	__ret := C.YGNodeLayoutGetTop(cnode)
	__v := (float32)(__ret)
	return __v
}

// NodeLayoutGetRight function as declared in yoga/Yoga.h:229
func NodeLayoutGetRight(node NodeRef) float32 {
	cnode, _ := *(*C.YGNodeRef)(unsafe.Pointer(&node)), cgoAllocsUnknown
	__ret := C.YGNodeLayoutGetRight(cnode)
	__v := (float32)(__ret)
	return __v
}

// NodeLayoutGetBottom function as declared in yoga/Yoga.h:230
func NodeLayoutGetBottom(node NodeRef) float32 {
	cnode, _ := *(*C.YGNodeRef)(unsafe.Pointer(&node)), cgoAllocsUnknown
	__ret := C.YGNodeLayoutGetBottom(cnode)
	__v := (float32)(__ret)
	return __v
}

// NodeLayoutGetWidth function as declared in yoga/Yoga.h:231
func NodeLayoutGetWidth(node NodeRef) float32 {
	cnode, _ := *(*C.YGNodeRef)(unsafe.Pointer(&node)), cgoAllocsUnknown
	__ret := C.YGNodeLayoutGetWidth(cnode)
	__v := (float32)(__ret)
	return __v
}

// NodeLayoutGetHeight function as declared in yoga/Yoga.h:232
func NodeLayoutGetHeight(node NodeRef) float32 {
	cnode, _ := *(*C.YGNodeRef)(unsafe.Pointer(&node)), cgoAllocsUnknown
	__ret := C.YGNodeLayoutGetHeight(cnode)
	__v := (float32)(__ret)
	return __v
}

// NodeLayoutGetDirection function as declared in yoga/Yoga.h:233
func NodeLayoutGetDirection(node NodeRef) Direction {
	cnode, _ := *(*C.YGNodeRef)(unsafe.Pointer(&node)), cgoAllocsUnknown
	__ret := C.YGNodeLayoutGetDirection(cnode)
	__v := (Direction)(__ret)
	return __v
}

// NodeLayoutGetHadOverflow function as declared in yoga/Yoga.h:234
func NodeLayoutGetHadOverflow(node NodeRef) bool {
	cnode, _ := *(*C.YGNodeRef)(unsafe.Pointer(&node)), cgoAllocsUnknown
	__ret := C.YGNodeLayoutGetHadOverflow(cnode)
	__v := (bool)(__ret)
	return __v
}

// NodeLayoutGetMargin function as declared in yoga/Yoga.h:240
func NodeLayoutGetMargin(node NodeRef, edge Edge) float32 {
	cnode, _ := *(*C.YGNodeRef)(unsafe.Pointer(&node)), cgoAllocsUnknown
	cedge, _ := (C.YGEdge)(edge), cgoAllocsUnknown
	__ret := C.YGNodeLayoutGetMargin(cnode, cedge)
	__v := (float32)(__ret)
	return __v
}

// NodeLayoutGetBorder function as declared in yoga/Yoga.h:241
func NodeLayoutGetBorder(node NodeRef, edge Edge) float32 {
	cnode, _ := *(*C.YGNodeRef)(unsafe.Pointer(&node)), cgoAllocsUnknown
	cedge, _ := (C.YGEdge)(edge), cgoAllocsUnknown
	__ret := C.YGNodeLayoutGetBorder(cnode, cedge)
	__v := (float32)(__ret)
	return __v
}

// NodeLayoutGetPadding function as declared in yoga/Yoga.h:242
func NodeLayoutGetPadding(node NodeRef, edge Edge) float32 {
	cnode, _ := *(*C.YGNodeRef)(unsafe.Pointer(&node)), cgoAllocsUnknown
	cedge, _ := (C.YGEdge)(edge), cgoAllocsUnknown
	__ret := C.YGNodeLayoutGetPadding(cnode, cedge)
	__v := (float32)(__ret)
	return __v
}

// Assert function as declared in yoga/Yoga.h:247
func Assert(condition bool, message string) {
	ccondition, _ := (C._Bool)(condition), cgoAllocsUnknown
	cmessage, _ := unpackPCharString(message)
	C.YGAssert(ccondition, cmessage)
}

// AssertWithNode function as declared in yoga/Yoga.h:248
func AssertWithNode(node NodeRef, condition bool, message string) {
	cnode, _ := *(*C.YGNodeRef)(unsafe.Pointer(&node)), cgoAllocsUnknown
	ccondition, _ := (C._Bool)(condition), cgoAllocsUnknown
	cmessage, _ := unpackPCharString(message)
	C.YGAssertWithNode(cnode, ccondition, cmessage)
}

// AssertWithConfig function as declared in yoga/Yoga.h:249
func AssertWithConfig(config ConfigRef, condition bool, message string) {
	cconfig, _ := *(*C.YGConfigRef)(unsafe.Pointer(&config)), cgoAllocsUnknown
	ccondition, _ := (C._Bool)(condition), cgoAllocsUnknown
	cmessage, _ := unpackPCharString(message)
	C.YGAssertWithConfig(cconfig, ccondition, cmessage)
}

// ConfigSetPointScaleFactor function as declared in yoga/Yoga.h:255
func ConfigSetPointScaleFactor(config ConfigRef, pixelsInPoint float32) {
	cconfig, _ := *(*C.YGConfigRef)(unsafe.Pointer(&config)), cgoAllocsUnknown
	cpixelsInPoint, _ := (C.float)(pixelsInPoint), cgoAllocsUnknown
	C.YGConfigSetPointScaleFactor(cconfig, cpixelsInPoint)
}

// ConfigSetUseLegacyStretchBehaviour function as declared in yoga/Yoga.h:263
func ConfigSetUseLegacyStretchBehaviour(config ConfigRef, useLegacyStretchBehaviour bool) {
	cconfig, _ := *(*C.YGConfigRef)(unsafe.Pointer(&config)), cgoAllocsUnknown
	cuseLegacyStretchBehaviour, _ := (C._Bool)(useLegacyStretchBehaviour), cgoAllocsUnknown
	C.YGConfigSetUseLegacyStretchBehaviour(cconfig, cuseLegacyStretchBehaviour)
}

// ConfigNew function as declared in yoga/Yoga.h:267
func ConfigNew() ConfigRef {
	__ret := C.YGConfigNew()
	__v := *(*ConfigRef)(unsafe.Pointer(&__ret))
	return __v
}

// ConfigFree function as declared in yoga/Yoga.h:268
func ConfigFree(config ConfigRef) {
	cconfig, _ := *(*C.YGConfigRef)(unsafe.Pointer(&config)), cgoAllocsUnknown
	C.YGConfigFree(cconfig)
}

// ConfigCopy function as declared in yoga/Yoga.h:269
func ConfigCopy(dest ConfigRef, src ConfigRef) {
	cdest, _ := *(*C.YGConfigRef)(unsafe.Pointer(&dest)), cgoAllocsUnknown
	csrc, _ := *(*C.YGConfigRef)(unsafe.Pointer(&src)), cgoAllocsUnknown
	C.YGConfigCopy(cdest, csrc)
}

// ConfigGetInstanceCount function as declared in yoga/Yoga.h:270
func ConfigGetInstanceCount() int32 {
	__ret := C.YGConfigGetInstanceCount()
	__v := (int32)(__ret)
	return __v
}

// ConfigSetExperimentalFeatureEnabled function as declared in yoga/Yoga.h:272
func ConfigSetExperimentalFeatureEnabled(config ConfigRef, feature ExperimentalFeature, enabled bool) {
	cconfig, _ := *(*C.YGConfigRef)(unsafe.Pointer(&config)), cgoAllocsUnknown
	cfeature, _ := (C.YGExperimentalFeature)(feature), cgoAllocsUnknown
	cenabled, _ := (C._Bool)(enabled), cgoAllocsUnknown
	C.YGConfigSetExperimentalFeatureEnabled(cconfig, cfeature, cenabled)
}

// ConfigIsExperimentalFeatureEnabled function as declared in yoga/Yoga.h:275
func ConfigIsExperimentalFeatureEnabled(config ConfigRef, feature ExperimentalFeature) bool {
	cconfig, _ := *(*C.YGConfigRef)(unsafe.Pointer(&config)), cgoAllocsUnknown
	cfeature, _ := (C.YGExperimentalFeature)(feature), cgoAllocsUnknown
	__ret := C.YGConfigIsExperimentalFeatureEnabled(cconfig, cfeature)
	__v := (bool)(__ret)
	return __v
}

// ConfigSetUseWebDefaults function as declared in yoga/Yoga.h:280
func ConfigSetUseWebDefaults(config ConfigRef, enabled bool) {
	cconfig, _ := *(*C.YGConfigRef)(unsafe.Pointer(&config)), cgoAllocsUnknown
	cenabled, _ := (C._Bool)(enabled), cgoAllocsUnknown
	C.YGConfigSetUseWebDefaults(cconfig, cenabled)
}

// ConfigGetUseWebDefaults function as declared in yoga/Yoga.h:281
func ConfigGetUseWebDefaults(config ConfigRef) bool {
	cconfig, _ := *(*C.YGConfigRef)(unsafe.Pointer(&config)), cgoAllocsUnknown
	__ret := C.YGConfigGetUseWebDefaults(cconfig)
	__v := (bool)(__ret)
	return __v
}

// ConfigSetNodeClonedFunc function as declared in yoga/Yoga.h:283
func ConfigSetNodeClonedFunc(config ConfigRef, callback NodeClonedFunc) {
	cconfig, _ := *(*C.YGConfigRef)(unsafe.Pointer(&config)), cgoAllocsUnknown
	ccallback, _ := callback.PassValue()
	C.YGConfigSetNodeClonedFunc(cconfig, ccallback)
}

// ConfigGetDefault function as declared in yoga/Yoga.h:287
func ConfigGetDefault() ConfigRef {
	__ret := C.YGConfigGetDefault()
	__v := *(*ConfigRef)(unsafe.Pointer(&__ret))
	return __v
}

// ConfigSetContext function as declared in yoga/Yoga.h:289
func ConfigSetContext(config ConfigRef, context unsafe.Pointer) {
	cconfig, _ := *(*C.YGConfigRef)(unsafe.Pointer(&config)), cgoAllocsUnknown
	ccontext, _ := context, cgoAllocsUnknown
	C.YGConfigSetContext(cconfig, ccontext)
}

// ConfigGetContext function as declared in yoga/Yoga.h:290
func ConfigGetContext(config ConfigRef) unsafe.Pointer {
	cconfig, _ := *(*C.YGConfigRef)(unsafe.Pointer(&config)), cgoAllocsUnknown
	__ret := C.YGConfigGetContext(cconfig)
	__v := *(*unsafe.Pointer)(unsafe.Pointer(&__ret))
	return __v
}

// RoundValueToPixelGrid function as declared in yoga/Yoga.h:292
func RoundValueToPixelGrid(value float32, pointScaleFactor float32, forceCeil bool, forceFloor bool) float32 {
	cvalue, _ := (C.float)(value), cgoAllocsUnknown
	cpointScaleFactor, _ := (C.float)(pointScaleFactor), cgoAllocsUnknown
	cforceCeil, _ := (C._Bool)(forceCeil), cgoAllocsUnknown
	cforceFloor, _ := (C._Bool)(forceFloor), cgoAllocsUnknown
	__ret := C.YGRoundValueToPixelGrid(cvalue, cpointScaleFactor, cforceCeil, cforceFloor)
	__v := (float32)(__ret)
	return __v
}

// AlignToString function as declared in yoga/YGEnums.h:25
func AlignToString(value Align) string {
	cvalue, _ := (C.YGAlign)(value), cgoAllocsUnknown
	__ret := C.YGAlignToString(cvalue)
	__v := packPCharString(__ret)
	return __v
}

// DimensionToString function as declared in yoga/YGEnums.h:32
func DimensionToString(value Dimension) string {
	cvalue, _ := (C.YGDimension)(value), cgoAllocsUnknown
	__ret := C.YGDimensionToString(cvalue)
	__v := packPCharString(__ret)
	return __v
}

// DirectionToString function as declared in yoga/YGEnums.h:40
func DirectionToString(value Direction) string {
	cvalue, _ := (C.YGDirection)(value), cgoAllocsUnknown
	__ret := C.YGDirectionToString(cvalue)
	__v := packPCharString(__ret)
	return __v
}

// DisplayToString function as declared in yoga/YGEnums.h:47
func DisplayToString(value Display) string {
	cvalue, _ := (C.YGDisplay)(value), cgoAllocsUnknown
	__ret := C.YGDisplayToString(cvalue)
	__v := packPCharString(__ret)
	return __v
}

// EdgeToString function as declared in yoga/YGEnums.h:61
func EdgeToString(value Edge) string {
	cvalue, _ := (C.YGEdge)(value), cgoAllocsUnknown
	__ret := C.YGEdgeToString(cvalue)
	__v := packPCharString(__ret)
	return __v
}

// ExperimentalFeatureToString function as declared in yoga/YGEnums.h:67
func ExperimentalFeatureToString(value ExperimentalFeature) string {
	cvalue, _ := (C.YGExperimentalFeature)(value), cgoAllocsUnknown
	__ret := C.YGExperimentalFeatureToString(cvalue)
	__v := packPCharString(__ret)
	return __v
}

// FlexDirectionToString function as declared in yoga/YGEnums.h:76
func FlexDirectionToString(value FlexDirection) string {
	cvalue, _ := (C.YGFlexDirection)(value), cgoAllocsUnknown
	__ret := C.YGFlexDirectionToString(cvalue)
	__v := packPCharString(__ret)
	return __v
}

// JustifyToString function as declared in yoga/YGEnums.h:87
func JustifyToString(value Justify) string {
	cvalue, _ := (C.YGJustify)(value), cgoAllocsUnknown
	__ret := C.YGJustifyToString(cvalue)
	__v := packPCharString(__ret)
	return __v
}

// LogLevelToString function as declared in yoga/YGEnums.h:98
func LogLevelToString(value LogLevel) string {
	cvalue, _ := (C.YGLogLevel)(value), cgoAllocsUnknown
	__ret := C.YGLogLevelToString(cvalue)
	__v := packPCharString(__ret)
	return __v
}

// MeasureModeToString function as declared in yoga/YGEnums.h:106
func MeasureModeToString(value MeasureMode) string {
	cvalue, _ := (C.YGMeasureMode)(value), cgoAllocsUnknown
	__ret := C.YGMeasureModeToString(cvalue)
	__v := packPCharString(__ret)
	return __v
}

// NodeTypeToString function as declared in yoga/YGEnums.h:113
func NodeTypeToString(value NodeType) string {
	cvalue, _ := (C.YGNodeType)(value), cgoAllocsUnknown
	__ret := C.YGNodeTypeToString(cvalue)
	__v := packPCharString(__ret)
	return __v
}

// OverflowToString function as declared in yoga/YGEnums.h:121
func OverflowToString(value Overflow) string {
	cvalue, _ := (C.YGOverflow)(value), cgoAllocsUnknown
	__ret := C.YGOverflowToString(cvalue)
	__v := packPCharString(__ret)
	return __v
}

// PositionTypeToString function as declared in yoga/YGEnums.h:128
func PositionTypeToString(value PositionType) string {
	cvalue, _ := (C.YGPositionType)(value), cgoAllocsUnknown
	__ret := C.YGPositionTypeToString(cvalue)
	__v := packPCharString(__ret)
	return __v
}

// PrintOptionsToString function as declared in yoga/YGEnums.h:136
func PrintOptionsToString(value PrintOptions) string {
	cvalue, _ := (C.YGPrintOptions)(value), cgoAllocsUnknown
	__ret := C.YGPrintOptionsToString(cvalue)
	__v := packPCharString(__ret)
	return __v
}

// UnitToString function as declared in yoga/YGEnums.h:145
func UnitToString(value Unit) string {
	cvalue, _ := (C.YGUnit)(value), cgoAllocsUnknown
	__ret := C.YGUnitToString(cvalue)
	__v := packPCharString(__ret)
	return __v
}

// WrapToString function as declared in yoga/YGEnums.h:153
func WrapToString(value Wrap) string {
	cvalue, _ := (C.YGWrap)(value), cgoAllocsUnknown
	__ret := C.YGWrapToString(cvalue)
	__v := packPCharString(__ret)
	return __v
}
