// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Sun, 28 Oct 2018 21:21:53 GMT.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

#include "Yoga.h"
#include <stdlib.h>
#pragma once

#define __CGOGEN 1

// YGMeasureFunc_ecadcdc6 is a proxy for callback YGMeasureFunc.
YGSize YGMeasureFunc_ecadcdc6(YGNodeRef node, float width, YGMeasureMode widthMode, float height, YGMeasureMode heightMode);

// YGBaselineFunc_e756b14a is a proxy for callback YGBaselineFunc.
float YGBaselineFunc_e756b14a(YGNodeRef node, float width, float height);

// YGDirtiedFunc_91998949 is a proxy for callback YGDirtiedFunc.
void YGDirtiedFunc_91998949(YGNodeRef node);

// YGPrintFunc_6b37638d is a proxy for callback YGPrintFunc.
void YGPrintFunc_6b37638d(YGNodeRef node);

// YGCloneNodeFunc_7c7b6182 is a proxy for callback YGCloneNodeFunc.
YGNodeRef YGCloneNodeFunc_7c7b6182(YGConfigRef config, YGNodeRef oldNode, YGNodeRef owner, int childIndex);

