// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Sun, 28 Oct 2018 21:21:53 GMT.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

#include "_cgo_export.h"
#include "cgo_helpers.h"

YGSize YGMeasureFunc_ecadcdc6(YGNodeRef node, float width, YGMeasureMode widthMode, float height, YGMeasureMode heightMode) {
	return measureFuncECADCDC6(node, width, widthMode, height, heightMode);
}

float YGBaselineFunc_e756b14a(YGNodeRef node, float width, float height) {
	return baselineFuncE756B14A(node, width, height);
}

void YGDirtiedFunc_91998949(YGNodeRef node) {
	dirtiedFunc91998949(node);
}

void YGPrintFunc_6b37638d(YGNodeRef node) {
	printFunc6B37638D(node);
}

YGNodeRef YGCloneNodeFunc_7c7b6182(YGConfigRef config, YGNodeRef oldNode, YGNodeRef owner, int childIndex) {
	return cloneNodeFunc7C7B6182(config, oldNode, owner, childIndex);
}

