// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Sun, 28 Oct 2018 21:21:53 GMT.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

/*
Package yoga provides Go bindings for Facebook, Inc's Yoga layout engine
*/
package yoga
