// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Sun, 28 Oct 2018 20:23:31 GMT.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

package yoga

/*
#cgo CFLAGS: -I../yoga
#cgo CXXFLAGS: -std=c++14 -g
#cgo LDFLAGS: -lm
#include "Yoga.h"
#include <stdlib.h>
#include "cgo_helpers.h"
*/
import "C"

// Size as declared in yoga/Yoga.h:38
type Size struct {
	Width         float32
	Height        float32
	ref626288d    *C.YGSize
	allocs626288d interface{}
}

// Value as declared in yoga/Yoga.h:43
type Value struct {
	Value          float32
	Unit           Unit
	ref23e8c9e3    *C.YGValue
	allocs23e8c9e3 interface{}
}

// ConfigRef as declared in yoga/Yoga.h:59
type ConfigRef C.YGConfigRef

// NodeRef as declared in yoga/Yoga.h:61
type NodeRef C.YGNodeRef

// MeasureFunc type as declared in yoga/Yoga.h:63
type MeasureFunc func(node NodeRef, width float32, widthMode MeasureMode, height float32, heightMode MeasureMode) Size

// BaselineFunc type as declared in yoga/Yoga.h:69
type BaselineFunc func(node NodeRef, width float32, height float32) float32

// DirtiedFunc type as declared in yoga/Yoga.h:71
type DirtiedFunc func(node NodeRef)

// PrintFunc type as declared in yoga/Yoga.h:72
type PrintFunc func(node NodeRef)

// CloneNodeFunc type as declared in yoga/Yoga.h:79
type CloneNodeFunc func(config ConfigRef, oldNode NodeRef, owner NodeRef, childIndex int32) NodeRef
